const form=document.getElementById('builderForm');const urlInput=document.getElementById('websiteUrl');const nameInput=document.getElementById('appName');const packageInput=document.getElementById('packageName');const iconFile=document.getElementById('iconFile');const iconPreview=document.getElementById('iconPreview');const iconTitle=document.getElementById('iconTitle');const errorBox=document.getElementById('errorBox');const buildSection=document.getElementById('buildSection');const progressBar=document.getElementById('progressBar');const progressText=document.getElementById('progressText');const progressPercent=document.getElementById('progressPercent');const buildLog=document.getElementById('buildLog');const buildState=document.getElementById('buildState');const downloadArea=document.getElementById('downloadArea');let iconData='';
nameInput.addEventListener('input',()=>document.getElementById('nameCount').textContent=`${nameInput.value.length}/30`);
iconFile.addEventListener('change',()=>{const file=iconFile.files[0];if(!file)return;if(file.size>3*1024*1024){showError('Icon must be smaller than 3 MB.');iconFile.value='';return}const reader=new FileReader();reader.onload=()=>{iconData=reader.result;iconPreview.innerHTML=`<img src="${iconData}" alt="App icon preview">`;iconTitle.textContent=file.name};reader.readAsDataURL(file)});
function showError(msg){errorBox.textContent=msg;errorBox.hidden=false}function clearError(){errorBox.hidden=true;errorBox.textContent=''}function normalizeUrl(value){let v=value.trim();if(!/^https?:\/\//i.test(v))v='https://'+v;return new URL(v)}function validPackage(value){return /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){2,}$/.test(value)}function log(msg){const line=document.createElement('div');line.textContent=`› ${msg}`;buildLog.appendChild(line)}
form.addEventListener('submit',async e=>{e.preventDefault();clearError();let url;try{url=normalizeUrl(urlInput.value)}catch{showError('Enter a valid website URL.');return}if(url.protocol!=='https:'){showError('For security, use an HTTPS website.');return}const name=nameInput.value.trim();const pkg=packageInput.value.trim();if(name.length<2){showError('Enter an app name.');return}if(!validPackage(pkg)){showError('Package name must look like com.company.app.');return}
buildSection.hidden=false;buildSection.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('resultName').textContent=name;document.getElementById('resultUrl').textContent=url.href;document.getElementById('resultPackage').textContent=pkg;const resultIcon=document.getElementById('resultIcon');resultIcon.innerHTML=iconData?`<img src="${iconData}" alt="">`:name[0].toUpperCase();progressBar.style.width='5%';progressPercent.textContent='5%';progressText.textContent='Starting secure build…';buildLog.innerHTML='';downloadArea.hidden=true;buildState.textContent='Starting';
log('Validating build request');await new Promise(r=>setTimeout(r,350));log('Sending configuration to secure build service');progressBar.style.width='25%';progressPercent.textContent='25%';
try{const response=await fetch('/api/build',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({website_url:url.toString(),app_name:name,package_name:pkg})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Could not start Android build');progressBar.style.width='100%';progressPercent.textContent='100%';progressText.textContent='Android build queued';buildState.textContent='Building';log('GitHub Actions runner accepted the build');log('Open the GitHub Actions run to download the signed APK artifact');downloadArea.hidden=false;downloadArea.querySelector('h3').textContent='Android build started';downloadArea.querySelector('p').textContent='The APK is compiling on the Android runner. The finished signed APK will be available as a GitHub Actions artifact when the build completes.'}catch(err){buildState.textContent='Error';progressText.textContent='Build could not start';showError(err.message);log('Build request failed')}});
document.getElementById('resetBtn').addEventListener('click',()=>{buildSection.hidden=true;form.reset();document.getElementById('nameCount').textContent='0/30';iconPreview.textContent='＋';iconTitle.textContent='Upload PNG/JPG';iconData='';clearError();window.scrollTo({top:0,behavior:'smooth'})});
