const form=document.getElementById('builderForm');const urlInput=document.getElementById('websiteUrl');const nameInput=document.getElementById('appName');const packageInput=document.getElementById('packageName');const iconFile=document.getElementById('iconFile');const iconPreview=document.getElementById('iconPreview');const iconTitle=document.getElementById('iconTitle');const errorBox=document.getElementById('errorBox');const buildSection=document.getElementById('buildSection');const progressBar=document.getElementById('progressBar');const progressText=document.getElementById('progressText');const progressPercent=document.getElementById('progressPercent');const buildLog=document.getElementById('buildLog');const buildState=document.getElementById('buildState');const downloadArea=document.getElementById('downloadArea');let iconData='';
nameInput.addEventListener('input',()=>document.getElementById('nameCount').textContent=`${nameInput.value.length}/30`);
iconFile.addEventListener('change',()=>{const file=iconFile.files[0];if(!file)return;if(file.size>3*1024*1024){showError('Icon must be smaller than 3 MB.');iconFile.value='';return}const reader=new FileReader();reader.onload=()=>{iconData=reader.result;iconPreview.innerHTML=`<img src="${iconData}" alt="App icon preview">`;iconTitle.textContent=file.name};reader.readAsDataURL(file)});
function showError(msg){errorBox.textContent=msg;errorBox.hidden=false}function clearError(){errorBox.hidden=true;errorBox.textContent=''}
function normalizeUrl(value){let v=value.trim();if(!/^https?:\/\//i.test(v))v='https://'+v;return new URL(v)}
function validPackage(value){return /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*){2,}$/.test(value)}
function log(msg){const line=document.createElement('div');line.textContent=`› ${msg}`;buildLog.appendChild(line)}
form.addEventListener('submit',async e=>{e.preventDefault();clearError();let url;try{url=normalizeUrl(urlInput.value)}catch{showError('Enter a valid website URL.');return}if(url.protocol!=='https:'){showError('For security, use an HTTPS website.');return}const name=nameInput.value.trim();if(name.length<2){showError('Enter an app name.');return}if(!validPackage(packageInput.value.trim())){showError('Package name must look like com.company.app.');return}
buildSection.hidden=false;buildSection.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('resultName').textContent=name;document.getElementById('resultUrl').textContent=url.href;document.getElementById('resultPackage').textContent=packageInput.value.trim();const resultIcon=document.getElementById('resultIcon');resultIcon.innerHTML=iconData?`<img src="${iconData}" alt="">`:name[0].toUpperCase();progressBar.style.width='0%';progressPercent.textContent='0%';progressText.textContent='Starting…';buildLog.innerHTML='';downloadArea.hidden=true;buildState.textContent='Preparing';
const steps=[['Validating website configuration',20],['Creating Android WebView configuration',42],['Applying app identity and icon',64],['Preparing Gradle build manifest',82],['Ready for Android runner',100]];for(const [text,pct] of steps){await new Promise(r=>setTimeout(r,500));progressBar.style.width=pct+'%';progressPercent.textContent=pct+'%';progressText.textContent=text;log(text)}buildState.textContent='Ready';progressText.textContent='Build configuration prepared';downloadArea.hidden=false;log('Android compilation endpoint can now consume this build manifest.');});
document.getElementById('resetBtn').addEventListener('click',()=>{buildSection.hidden=true;form.reset();document.getElementById('nameCount').textContent='0/30';iconPreview.textContent='＋';iconTitle.textContent='Upload PNG/JPG';iconData='';clearError();window.scrollTo({top:0,behavior:'smooth'})});
